### ISSUE TITLE
Sobre a logica do admin

### ISSUE THREAD

**Issue by F-Jackson** [DigitalsysTecnologia/challenge-django-consultant#1]
No teste diz: O sistema deve oferecer flexibilidade para que o admin do sistema possa configurar quais os campos que a proposta deve conter, ou seja, caberá a alguém de dentro da empresa definir o que deverá ser pedido de informação para o solicitante da proposta.

Isso quer dizer que a pessoa pode fazer um crud? Ou seria só um marcar um campo ja pre definido pelos models como sendo necessario e vai ser enviado para a api de loan?

**Comment by oedudev** [comment]
Ola, boa tarde,

Isso quer dizer que deve haver um cadastro no admin onde um usuário sem acesso ao código fonte possa escolher quais campos devem constar na proposta (Ex: Nome da Mãe, CPF, Data de Nascimento, etc).
